/// @file
#pragma once
#ifndef HEADER_MousePairOfInt_INCLUDED
#define HEADER_MousePairOfInt_INCLUDED

#include "Agent_class.pde.hpp"
#include "World_class.pde.hpp"

/// Simple version of Pair returning a pair of Int.

/// @note Automatically extracted definition of `class`: MousePairOfInt
class MousePairOfInt: public virtual Object{
  public:

    int a;
    int b;

    MousePairOfInt(int a,int b) 
    {
        this->a = a;
        this->b = b;
    }
} ;/*_endOfClass*/

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_MousePairOfInt_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:05 !

