/// @file
#pragma once
/// @date 2024-10-15 (last change)
#ifndef HEADER_Animal_INCLUDED
#define HEADER_Animal_INCLUDED

#include "Face_class.pde.hpp"

/// @note Automatically extracted definition of `class`: Animal
//abstract
class Animal : public virtual Face , public virtual Object{
  public:

    float mass;
    virtual  void eat(int l) {
        println(l,"Animal eats"); 
        mass+=l;
    }
    
    String face() {
	 return "👾" ;
	}

} ; //_EndOfClass_


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_Animal_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:03 !

