/// @file
#pragma once
/// @date 2024-10-15 (last change)
#ifndef HEADER_AnimalFeeder_INCLUDED
#define HEADER_AnimalFeeder_INCLUDED

/// @note Automatically extracted definition of `class`: AnimalFeeder
class AnimalFeeder: public virtual Object{
  public:

    void feed(pArrayList<pAnimal> animals) {
        for(pAnimal a:animals)
            a->eat(10);
        }
} ; //_EndOfClass_


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_AnimalFeeder_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:03 !

