/// @file
#pragma once
/// @date 2024-10-15 (last change)
#ifndef HEADER_Cat_INCLUDED
#define HEADER_Cat_INCLUDED

#include "Face_class.pde.hpp"
#include "Mew_class.pde.hpp"

#include "Animal_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: Cat

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:Cat

class Cat : public  Animal, public virtual Face,public virtual Mew, public virtual Eat , public virtual Object{
  public:

    void eat(int l) {
         println(l,"Cat eats");  
    }
 
    void meow(int l) {
         println(l,"Cat meows");  
    }
    
    String face() {
	 return "🐱"; 
	}
} ; //_EndOfClass_


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_Cat_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:03 !

