/// @file
#pragma once
/// @date 2024-10-15 (last change)
#ifndef HEADER_Dog_INCLUDED
#define HEADER_Dog_INCLUDED

#include "Animal_class.pde.hpp"
//Base class is now:
#define _superclass _

/// @note Automatically extracted definition of `class`: Dog

//_endOfSuperClass; // Now will change of superclass!
//Base class is now:
#define _superclass _
//_derivedClass:Dog

class Dog : public  Animal  , public virtual Object{
  public:

    void eat(int l) {
         println(l,"Dog eats");  
    }
    
    String face() {
	 return "🐶"; 
	}
} ; //_EndOfClass_


//Undefining any base class preprocessor definition: _
#undef _superclass

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_Dog_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:03 !

