/// @file
#pragma once
/// @date 2024-10-15 (last change)
#ifndef HEADER_Eat_INCLUDED
#define HEADER_Eat_INCLUDED

/// @note Automatically extracted definition of `class`: Eat
//interface
class Eat: public virtual Object{
  public:

    virtual  void eat(int l) =0 ;
} ; //_EndOfClass_


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_Eat_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:03 !

