/// @file
#pragma once
/// @date 2024-10-15 (last change)
#ifndef HEADER_Face_INCLUDED
#define HEADER_Face_INCLUDED

/// Class hierarchy test for Processing2C.
/// ORIGINAL FILE: "CLASSTEST.pde"
/// INSPIRED BY EXAMPLE from https://www->baeldung->com/java-type-casting

/// @note Automatically extracted definition of `class`: Face
//interface
class Face: public virtual Object{
  public:

     virtual  String face() =0 ;
} ; //_EndOfClass_


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_Face_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:03 !

