/// @file
#pragma once
/// @date 2024-10-15 (last change)
#ifndef HEADER_Mew_INCLUDED
#define HEADER_Mew_INCLUDED

/// @note Automatically extracted definition of `class`: Mew
//interface
class Mew: public virtual Object{
  public:

    virtual  void meow(int l) =0 ;
} ; //_EndOfClass_


/// Generated by Processing2C++ extraction Tools
#endif //HEADER_Mew_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:03 !

