//_pragma once
//_ifndef HEADER_MousePairOfInt_INCLUDED
//_define HEADER_MousePairOfInt_INCLUDED

/*_import_class:Agent */
/*_import_class:World */

/// Simple version of Pair returning a pair of Int.

/// @note Automatically extracted definition of `class`: MousePairOfInt
class MousePairOfInt {

    int a;
    int b;

    MousePairOfInt(int a,int b) 
    {
        this.a = a;
        this.b = b;
    }
} /*_endOfClass*/

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_MousePairOfInt_INCLUDED

