//_pragma once
/// @date 2024-10-15 (last modification)
//_ifndef HEADER_World_INCLUDED
//_define HEADER_World_INCLUDED

/*_import_class:Agent */

/// World is a one of two central class of each ABM model.
/// @details 
///         We have two layer - environment resources cells and agents. 
///         

/// @note Automatically extracted definition of `class`: World
class World {

  int[][]     cells;  //!< Two dimensional array of resources
  Agent[][]   agents; //!< Two dimensional array of agents
  
  World(int side)     //!< Constructor of the World
  {
    cells=new int[side][side];
    agents=new Agent[side][side];
  }
};

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_World_INCLUDED

