/// @file
#pragma once
/// @date 2024-10-15 (last change)
#ifndef HEADER_myTest_INCLUDED
#define HEADER_myTest_INCLUDED

/// @file
/// Test for HashMaps
/// ORIGINAL FILE: "MAPTEST.pde"
/// "file:///home/borkowsk/processing-3.5.4/modes/java/reference/HashMap.html"

/// @note Automatically extracted definition of `class`: myTest
class myTest: public virtual Object{
  public:

  int A;float B;
  myTest(int iA,float iB)
  {
    A=iA;B=iB;
  }
};

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_myTest_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:04 !

