//_pragma once
/// @date 2024-09-30 (last change)
//_ifndef HEADER_World_INCLUDED
//_define HEADER_World_INCLUDED

/// ABM (Agent Base Modeling) minimum template test for Processing2C
/// ORIGINAL FILE: AssemblingOfWorld.pde
/// World is a one of two central class of each ABM model

/// @note Automatically extracted definition of `class`: World
class World {

  //Agent[] agents; //JEDNOWYMIAROWA TABLICA AGENTÓW
  //OR
  Agent[][] agents; //DWUWYMIAROWA TABLICA AGENTÓW
  
  World(int side) //KONSTRUKTOR ŚWIATA
  {
    //agents=new Agent[side];
    //OR
    agents=new Agent[side][2*side];
  }
};

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_World_INCLUDED

