//_pragma once
/// @date 2024-10-14 (last change)
//_ifndef HEADER_AnimalFeeder_INCLUDED
//_define HEADER_AnimalFeeder_INCLUDED

/// @note Automatically extracted definition of `class`: AnimalFeeder
class AnimalFeeder  {

    void feed(ArrayList<Animal> animals) {
        for(Animal a:animals)
            a.eat(10);
        }
} //_endOfclass

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_AnimalFeeder_INCLUDED

