//_pragma once
/// @date 2024-10-14 (last change)
//_ifndef HEADER_Animal_INCLUDED
//_define HEADER_Animal_INCLUDED

/*_import_class:Face */

/// @note Automatically extracted definition of `class`: Animal
abstract class Animal implements Face {

    float mass;
    /*_interfunc*/ void eat(int l) {
        println(l,"Animal eats"); 
        mass+=l;
    }
    
    String face() { return "👾" ;}

} //_endOfclass

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_Animal_INCLUDED

