//_pragma once
/// @date 2024-10-14 (last change)
//_ifndef HEADER_Cat_INCLUDED
//_define HEADER_Cat_INCLUDED

/*_import_class:Face */
/*_import_class:Mew */

/*_import_class:Animal */
//_superclass:Animal

/// @note Automatically extracted definition of `class`: Cat
class Cat extends Animal implements Face,/*_pubext*/ Mew, /*_pubext*/ Eat {

    void eat(int l) {
         println(l,"Cat eats");  
    }
 
    void meow(int l) {
         println(l,"Cat meows");  
    }
    
    String face() { return "🐱"; }
} //_endOfclass

//_endOfSuperClass:Animal

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_Cat_INCLUDED

