//_pragma once
/// @date 2024-10-14 (last change)
//_ifndef HEADER_Dog_INCLUDED
//_define HEADER_Dog_INCLUDED

/*_import_class:Animal */
//_superclass:Animal

/// @note Automatically extracted definition of `class`: Dog
class Dog extends Animal  {

    void eat(int l) {
         println(l,"Dog eats");  
    }
    
    String face() { return "🐶"; }
} //_endOfclass

//_endOfSuperClass:Animal

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_Dog_INCLUDED

