//_pragma once
/// @date 2024-10-14 (last change)
//_ifndef HEADER_Eat_INCLUDED
//_define HEADER_Eat_INCLUDED

/// @note Automatically extracted definition of `class`: Eat
interface Eat  {

    /*_interfunc*/ void eat(int l) /*_forcebody*/ ;
} //_endOfclass

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_Eat_INCLUDED

