//_pragma once
/// @date 2024-10-14 (last change)
//_ifndef HEADER_Face_INCLUDED
//_define HEADER_Face_INCLUDED

/// Class hierarchy test for Processing2C.
/// ORIGINAL FILE: "CLASSTEST.pde"
/// INSPIRED BY EXAMPLE from https://www.baeldung.com/java-type-casting

/// @note Automatically extracted definition of `class`: Face
interface Face  {

     /*_interfunc*/ String face() /*_forcebody*/ ;
} //_endOfclass

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_Face_INCLUDED

