//_pragma once
/// @date 2024-10-14 (last change)
//_ifndef HEADER_Mew_INCLUDED
//_define HEADER_Mew_INCLUDED

/// @note Automatically extracted definition of `class`: Mew
interface Mew  {

    /*_interfunc*/ void meow(int l) /*_forcebody*/ ;
} //_endOfclass

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_Mew_INCLUDED

