//_pragma once
/// @date 2024-09-30 (last change)
//_ifndef HEADER_myTest_INCLUDED
//_define HEADER_myTest_INCLUDED

/// @file
/// Test for HashMaps
/// ORIGINAL FILE: "MAPTEST.pde"
/// "file:///home/borkowsk/processing-3.5.4/modes/java/reference/HashMap.html"

/// @note Automatically extracted definition of `class`: myTest
class myTest {

  int A;float B;
  myTest(int iA,float iB)
  {
    A=iA;B=iB;
  }
};

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_myTest_INCLUDED

