//_pragma once
/// @date 2024-09-30 (last change)
//_ifndef HEADER_C_INCLUDED
//_define HEADER_C_INCLUDED

/// @file
/// Test dla problemu z użyciem "this" jako parametru funkcji oczekujących `Processing::ptr<...>`.
/// Klasa testowa.

/// @note Automatically extracted definition of `class`: C
class C {

  C(int ii){ i=ii;}
  int i;
  /// Metoda ma dostęp do `this`.
  void call_inside(String msg)
  {
     call_outside(this,msg);    /// @internal Wołanie mietody zewnętrznej, która wymaga podania `this`.
  }
};

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_C_INCLUDED

