/// @file
#pragma once
/// @file
/// @date 2024-10-14 (last change)
#ifndef HEADER_World_INCLUDED
#define HEADER_World_INCLUDED

#include "Agent_class.pde.hpp"

/// @brief World is a one of two central class of each ABM model.

/// @note Automatically extracted definition of `class`: World
class World: public virtual Object{
  public:

  //sarray<pAgent> agents; //!< One dimensional array of agents.
  //OR
  smatrix<pAgent> agents; //!< Two dimensional array of agents.
  
  World(int side)   //!< Constructor of the World.
  {
    //agents=new array<pAgent>(side);
    //OR
    agents=new matrix<pAgent>(side,side);
  }
};

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_World_INCLUDED

//MADE NOTE: /data/wb/SCC/public/Processing2C/scripts did it 2024-10-14 17:32:20 !

