/// @file
#pragma once
/// @date 2024-10-15 (last change)
#ifndef HEADER_World_INCLUDED
#define HEADER_World_INCLUDED

/// ABM (Agent Base Modeling) minimum template test for Processing2C
/// ORIGINAL FILE: AssemblingOfWorld->pde
/// World is a one of two central class of each ABM model

/// @note Automatically extracted definition of `class`: World
class World: public virtual Object{
  public:

  //sarray<pAgent> agents; //JEDNOWYMIAROWA TABLICA AGENTÓW
  //OR
  smatrix<pAgent> agents; //DWUWYMIAROWA TABLICA AGENTÓW
  
  World(int side) //KONSTRUKTOR ŚWIATA
  {
    //agents=new array<pAgent>(side);
    //OR
    agents=new matrix<pAgent>(side,2*side);
  }
};

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_World_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:03 !

