//_pragma once
/// @file
/// @date 2024-10-14 (last change)
//_ifndef HEADER_World_INCLUDED
//_define HEADER_World_INCLUDED

/*_import_class:Agent */

/// @brief World is a one of two central class of each ABM model.

/// @note Automatically extracted definition of `class`: World
class World {

  //Agent[] agents; //!< One dimensional array of agents.
  //OR
  Agent[][] agents; //!< Two dimensional array of agents.
  
  World(int side)   //!< Constructor of the World.
  {
    //agents=new Agent[side];
    //OR
    agents=new Agent[side][side];
  }
};

/// Generated by Processing2C++ extraction Tools
//_endif //HEADER_World_INCLUDED

