/// @file
#pragma once
/// @date 2024-10-15 (last change)
#ifndef HEADER_C_INCLUDED
#define HEADER_C_INCLUDED

/// @file
/// Test dla problemu z użyciem "this" jako parametru funkcji oczekujących `Processing::ptr<...>`.
/// Klasa testowa.

/// @note Automatically extracted definition of `class`: C
class C: public virtual Object{
  public:

  C(int ii){ i=ii;}
  int i;
  /// Metoda ma dostęp do `this`.
  void call_inside(String msg)
  {
     call_outside(SAFE_THIS,msg);    /// @internal Wołanie mietody zewnętrznej, która wymaga podania `this`.
  }
};

/// Generated by Processing2C++ extraction Tools
#endif //HEADER_C_INCLUDED

//MADE NOTE: ../../scripts did it 2024-10-15 16:11:05 !

